# Generated by Django 5.1.7 on 2025-04-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('National', 'National'), ('Politics', 'Politics'), ('Sports', 'Sports')], default='Sports', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
